In [1]:
# Bismillah

In [2]:
import numpy as np
import pandas as pd
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('precision', 7)
from pandas_datareader import data

In [3]:
msft = data.DataReader('MSFT', 'yahoo', '2012-01-01', '2013-12-30')
msft

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6678486
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1777744
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.4044075
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7524548
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4529667
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.4010334
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7954731
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.1041756
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9755573
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9755573

### Shifting and lagging time-series data:

In [4]:
msftAC = msft['Adj Close']
msftAC.head()

Date
2012-01-03    21.6678486
2012-01-04    22.1777744
2012-01-05    22.4044075
2012-01-06    22.7524548
2012-01-09    22.4529667
Name: Adj Close, dtype: float64

In [5]:
shift_forward = msftAC.shift(1)
shift_forward.head()
# This will shift the prices one day forward.
# results in one NaN value at the start since there was no value prior to be shifted to 2012-01-03.
# the number of NaN values will depend on the number of indices we are shifting forward or backward. For instance, the index is 
# daily dates, so if we shift one day forward, it means we are forwarding one index resulting into one NaN value. If we would 
# shift 2 days forward, it means we are forwarding two indices resulting into two NaN values.

Date
2012-01-03           NaN
2012-01-04    21.6678486
2012-01-05    22.1777744
2012-01-06    22.4044075
2012-01-09    22.7524548
Name: Adj Close, dtype: float64

In [6]:
msftAC.tail(), shift_forward.tail()
# the last price 31.9755402 on date 2013-12-30 in msftAC has been lost away in shift_forward since there is no index available for
# it now after the prices have been shifted one day forward. So, we got one NaN value at the start and one value lost at the end
# by shifting one day forward.

(Date
 2013-12-23    31.4010334
 2013-12-24    31.7954731
 2013-12-26    32.1041756
 2013-12-27    31.9755573
 2013-12-30    31.9755573
 Name: Adj Close, dtype: float64,
 Date
 2013-12-23    31.5553856
 2013-12-24    31.4010334
 2013-12-26    31.7954731
 2013-12-27    32.1041756
 2013-12-30    31.9755573
 Name: Adj Close, dtype: float64)

In [7]:
shift_backward = msftAC.shift(-2)
# will shift two days (two indices) backward.

In [8]:
msftAC, shift_backward
# inserts two NaNs at the end since we have shifted two days (two indices) backward and the first two values lost since there are 
# no indices available for them.

(Date
 2012-01-03    21.6678486
 2012-01-04    22.1777744
 2012-01-05    22.4044075
 2012-01-06    22.7524548
 2012-01-09    22.4529667
                  ...
 2013-12-23    31.4010334
 2013-12-24    31.7954731
 2013-12-26    32.1041756
 2013-12-27    31.9755573
 2013-12-30    31.9755573
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03    22.4044075
 2012-01-04    22.7524548
 2012-01-05    22.4529667
 2012-01-06    22.5339127
 2012-01-09    22.4367809
                  ...
 2013-12-23    32.1041756
 2013-12-24    31.9755573
 2013-12-26    31.9755573
 2013-12-27           NaN
 2013-12-30           NaN
 Name: Adj Close, Length: 501, dtype: float64)

In [9]:
shift_1sec = msftAC.shift(1, freq = 'S')

In [10]:
msftAC, shift_1sec
# the prices have been shifted just one second forward each day. That means that the prices still exist on the same date. So, no
# value is lost and no NaN is inserted.
# the frequency could be changed to any desirable level such as hour etc.
# Note that the index labels have been adjusted according to the specified frequency resulting into a new dataframe or series in 
# this case.

(Date
 2012-01-03    21.6678486
 2012-01-04    22.1777744
 2012-01-05    22.4044075
 2012-01-06    22.7524548
 2012-01-09    22.4529667
                  ...
 2013-12-23    31.4010334
 2013-12-24    31.7954731
 2013-12-26    32.1041756
 2013-12-27    31.9755573
 2013-12-30    31.9755573
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03 00:00:01    21.6678486
 2012-01-04 00:00:01    22.1777744
 2012-01-05 00:00:01    22.4044075
 2012-01-06 00:00:01    22.7524548
 2012-01-09 00:00:01    22.4529667
                           ...
 2013-12-23 00:00:01    31.4010334
 2013-12-24 00:00:01    31.7954731
 2013-12-26 00:00:01    32.1041756
 2013-12-27 00:00:01    31.9755573
 2013-12-30 00:00:01    31.9755573
 Name: Adj Close, Length: 501, dtype: float64)

In [11]:
shift_1sec['2012-01-03':'2012-01-06']
# note that the indices now include the time as well in addition to the date.

Date
2012-01-03 00:00:01    21.6678486
2012-01-04 00:00:01    22.1777744
2012-01-05 00:00:01    22.4044075
2012-01-06 00:00:01    22.7524548
Name: Adj Close, dtype: float64

In [12]:
tshift_forward = msftAC.tshift(1, freq = "D")

C:\Users\MUSADA~1\AppData\Local\Temp/ipykernel_8908/3266092570.py:1: FutureWarning: tshift is deprecated and will be removed in a future version. Please use shift instead.
  tshift_forward = msftAC.tshift(1, freq = "D")

In [13]:
msftAC, tshift_forward
# should not use this since the indices have changed. For instance, '2012-01-07' does not exist in msftAC but now it exists in 
# tshift_forward. Also, '2012-01-09' has disappeared in the tshift_forward. There are other similar problems.

(Date
 2012-01-03    21.6678486
 2012-01-04    22.1777744
 2012-01-05    22.4044075
 2012-01-06    22.7524548
 2012-01-09    22.4529667
                  ...
 2013-12-23    31.4010334
 2013-12-24    31.7954731
 2013-12-26    32.1041756
 2013-12-27    31.9755573
 2013-12-30    31.9755573
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-04    21.6678486
 2012-01-05    22.1777744
 2012-01-06    22.4044075
 2012-01-07    22.7524548
 2012-01-10    22.4529667
                  ...
 2013-12-24    31.4010334
 2013-12-25    31.7954731
 2013-12-27    32.1041756
 2013-12-28    31.9755573
 2013-12-31    31.9755573
 Name: Adj Close, Length: 501, dtype: float64)

### Practical Example:

In [14]:
msftAC, msftAC.shift(1)
# the prices have been shifted one day forward.

(Date
 2012-01-03    21.6678486
 2012-01-04    22.1777744
 2012-01-05    22.4044075
 2012-01-06    22.7524548
 2012-01-09    22.4529667
                  ...
 2013-12-23    31.4010334
 2013-12-24    31.7954731
 2013-12-26    32.1041756
 2013-12-27    31.9755573
 2013-12-30    31.9755573
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6678486
 2012-01-05    22.1777744
 2012-01-06    22.4044075
 2012-01-09    22.7524548
                  ...
 2013-12-23    31.5553856
 2013-12-24    31.4010334
 2013-12-26    31.7954731
 2013-12-27    32.1041756
 2013-12-30    31.9755573
 Name: Adj Close, Length: 501, dtype: float64)

In [15]:
msftAC / msftAC.shift(1)
# the dividsion is based on the same index labels. That is, the price on 2012-01-04 in msftAC is divided the price on 2012-01-04 in
# msftAC.shift(1). This is equal current price divided by previous price (the amount invested).
# Interpretation: the $1 invested has grown to $1.0235337. So, the net return is $1.0235337 - 1 = $0.0235337. That is why we need
# to subtract 1 as shown below.
# the first value is NaN because value is missing in msftAC.shift(1) on 2012-01-03.
# the last value is 1.00000 because in both msftAC and msftAC.shift(1) the value on 2013-12-30 is the same.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0102189
2012-01-06    1.0155348
2012-01-09    0.9868371
                ...
2013-12-23    0.9951085
2013-12-24    1.0125614
2013-12-26    1.0097090
2013-12-27    0.9959937
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [16]:
percent_change = msftAC / msftAC.shift(1) - 1
percent_change
# gives the net change or return.
# the price has increased by 2.3% from 2012-01-03 to 2012-01-04.

Date
2012-01-03          NaN
2012-01-04    0.0235338
2012-01-05    0.0102189
2012-01-06    0.0155348
2012-01-09   -0.0131629
                ...
2013-12-23   -0.0048915
2013-12-24    0.0125614
2013-12-26    0.0097090
2013-12-27   -0.0040063
2013-12-30    0.0000000
Name: Adj Close, Length: 501, dtype: float64

### Frequency Conversion of Time-Series Data:

In [17]:
sample = msftAC[:2]
sample
# selected first 2 rows and stored them in 'sample'

Date
2012-01-03    21.6678486
2012-01-04    22.1777744
Name: Adj Close, dtype: float64

In [18]:
sample.asfreq('H')
# to have hourly data between the two index labels.
# a new index with hourly index labels has been created by pandas, but when aligning to the original time series, only two values
# were found, thereby leaving the others filled with NaN. This default behaviour can be changed as follows:

Date
2012-01-03 00:00:00    21.6678486
2012-01-03 01:00:00           NaN
2012-01-03 02:00:00           NaN
2012-01-03 03:00:00           NaN
2012-01-03 04:00:00           NaN
2012-01-03 05:00:00           NaN
2012-01-03 06:00:00           NaN
2012-01-03 07:00:00           NaN
2012-01-03 08:00:00           NaN
2012-01-03 09:00:00           NaN
2012-01-03 10:00:00           NaN
2012-01-03 11:00:00           NaN
2012-01-03 12:00:00           NaN
2012-01-03 13:00:00           NaN
2012-01-03 14:00:00           NaN
2012-01-03 15:00:00           NaN
2012-01-03 16:00:00           NaN
2012-01-03 17:00:00           NaN
2012-01-03 18:00:00           NaN
2012-01-03 19:00:00           NaN
2012-01-03 20:00:00           NaN
2012-01-03 21:00:00           NaN
2012-01-03 22:00:00           NaN
2012-01-03 23:00:00           NaN
2012-01-04 00:00:00    22.1777744
Freq: H, Name: Adj Close, dtype: float64

In [19]:
sample.asfreq('H', method = 'ffill')
# forward fill will take the earlier known value and fill all the missing values with it.

Date
2012-01-03 00:00:00    21.6678486
2012-01-03 01:00:00    21.6678486
2012-01-03 02:00:00    21.6678486
2012-01-03 03:00:00    21.6678486
2012-01-03 04:00:00    21.6678486
2012-01-03 05:00:00    21.6678486
2012-01-03 06:00:00    21.6678486
2012-01-03 07:00:00    21.6678486
2012-01-03 08:00:00    21.6678486
2012-01-03 09:00:00    21.6678486
2012-01-03 10:00:00    21.6678486
2012-01-03 11:00:00    21.6678486
2012-01-03 12:00:00    21.6678486
2012-01-03 13:00:00    21.6678486
2012-01-03 14:00:00    21.6678486
2012-01-03 15:00:00    21.6678486
2012-01-03 16:00:00    21.6678486
2012-01-03 17:00:00    21.6678486
2012-01-03 18:00:00    21.6678486
2012-01-03 19:00:00    21.6678486
2012-01-03 20:00:00    21.6678486
2012-01-03 21:00:00    21.6678486
2012-01-03 22:00:00    21.6678486
2012-01-03 23:00:00    21.6678486
2012-01-04 00:00:00    22.1777744
Freq: H, Name: Adj Close, dtype: float64

In [20]:
sample.asfreq('H', method = 'bfill')
# backward fill will take the next known value and fill the missing values in the backward direction.

Date
2012-01-03 00:00:00    21.6678486
2012-01-03 01:00:00    22.1777744
2012-01-03 02:00:00    22.1777744
2012-01-03 03:00:00    22.1777744
2012-01-03 04:00:00    22.1777744
2012-01-03 05:00:00    22.1777744
2012-01-03 06:00:00    22.1777744
2012-01-03 07:00:00    22.1777744
2012-01-03 08:00:00    22.1777744
2012-01-03 09:00:00    22.1777744
2012-01-03 10:00:00    22.1777744
2012-01-03 11:00:00    22.1777744
2012-01-03 12:00:00    22.1777744
2012-01-03 13:00:00    22.1777744
2012-01-03 14:00:00    22.1777744
2012-01-03 15:00:00    22.1777744
2012-01-03 16:00:00    22.1777744
2012-01-03 17:00:00    22.1777744
2012-01-03 18:00:00    22.1777744
2012-01-03 19:00:00    22.1777744
2012-01-03 20:00:00    22.1777744
2012-01-03 21:00:00    22.1777744
2012-01-03 22:00:00    22.1777744
2012-01-03 23:00:00    22.1777744
2012-01-04 00:00:00    22.1777744
Freq: H, Name: Adj Close, dtype: float64

### Resampling of time-series:

In [21]:
msftAC / msftAC.shift()
# I haven't confirmed it but i think the default argument for shift is 1 which means to shift prices forward by one day.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0102189
2012-01-06    1.0155348
2012-01-09    0.9868371
                ...
2013-12-23    0.9951085
2013-12-24    1.0125614
2013-12-26    1.0097090
2013-12-27    0.9959937
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [22]:
(1 + (msftAC / msftAC.shift() - 1))
# this and immediately above seems to produce the same result. Plus1 and minus1 cancels out so the result is the same as immediately above.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0102189
2012-01-06    1.0155348
2012-01-09    0.9868371
                ...
2013-12-23    0.9951085
2013-12-24    1.0125614
2013-12-26    1.0097090
2013-12-27    0.9959937
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [23]:
msft_cum_ret = (1 + (msftAC / msftAC.shift() - 1)).cumprod()
msft_cum_ret
# cumprod stands for cummulative product.
# it multiplies the value on 2012-01-04 with the value on 2012-01-05 and produces the product in the index label 2012-01-05. This product 
# can be called cumulative daily return.
# $1 dollar invested on 2012-01-03 has grown to $1.475 on 2013-12-30.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339932
2012-01-06    1.0500560
2012-01-09    1.0362342
                ...
2013-12-23    1.4491994
2013-12-24    1.4674033
2013-12-26    1.4816504
2013-12-27    1.4757145
2013-12-30    1.4757145
Name: Adj Close, Length: 501, dtype: float64

In [24]:
msft_cum_ret['1/1/2012':'1/31/2012']
# note that typing the date in this pattern is the same as typing 2012-01-04 and so on.
# this gives us daily cumulative returns for all the month as explained above.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339932
2012-01-06    1.0500560
2012-01-09    1.0362342
2012-01-10    1.0399700
2012-01-11    1.0354872
2012-01-12    1.0459467
2012-01-13    1.0552858
2012-01-17    1.0556593
2012-01-18    1.0545383
2012-01-19    1.0504296
2012-01-20    1.1098240
2012-01-23    1.1105714
2012-01-24    1.0960029
2012-01-25    1.1042209
2012-01-26    1.1019797
2012-01-27    1.0918939
2012-01-30    1.1060887
2012-01-31    1.1031004
Name: Adj Close, dtype: float64

In [25]:
msft_cum_ret['1/1/2012':'1/31/2012'].mean()
# mean cumulative return of January 2012. It is a mean of all the daily cumulative returns in January.
# to calculate each month mean cumulative return, we have to write this command 24 times for all 24 months.

1.0686745282176842

In [26]:
msft_cum_ret['1/2012'].mean()
# an alternative to the above method to compute monthly mean.

1.0686745282176842

In [27]:
msft_monthly_cum_ret = msft_cum_ret.resample("M")
msft_monthly_cum_ret
# a better and efficient alternative to the above two methods to compute monthly means.
# does not return a dataframe any longer but an object stored at some location in memory. Nevermind, all the aggregation and interpolation
# can still be validly performed as shown below.

In [28]:
def print_info(groupobject):
    for i, k in groupobject:
        print (i)
        print (k)

In [29]:
print_info(msft_monthly_cum_ret)
# the daily cumulative returns have been grouped by month. In total, we will have 24 groups since we have 24 months.

2012-01-31 00:00:00
Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339932
2012-01-06    1.0500560
2012-01-09    1.0362342
2012-01-10    1.0399700
2012-01-11    1.0354872
2012-01-12    1.0459467
2012-01-13    1.0552858
2012-01-17    1.0556593
2012-01-18    1.0545383
2012-01-19    1.0504296
2012-01-20    1.1098240
2012-01-23    1.1105714
2012-01-24    1.0960029
2012-01-25    1.1042209
2012-01-26    1.1019797
2012-01-27    1.0918939
2012-01-30    1.1060887
2012-01-31    1.1031004
Name: Adj Close, dtype: float64
2012-02-29 00:00:00
Date
2012-02-01    1.1165484
2012-02-02    1.1187896
2012-02-03    1.1296224
2012-02-06    1.1281283
2012-02-07    1.1337316
2012-02-08    1.1453116
2012-02-09    1.1494205
2012-02-10    1.1393348
2012-02-13    1.1423234
2012-02-14    1.1374353
2012-02-15    1.1299150
2012-02-16    1.1765404
2012-02-17    1.1750364
2012-02-21    1.1821806
2012-02-22    1.1757885
2012-02-23    1.1795486
2012-02-24    1.1836846
2012-02-27    1.1787963
2012-02-28    1.1983494
2012-02-29    1.1934612
Name: Adj Close, dtype: float64
2012-03-31 00:00:00
Date
2012-03-01    1.2141412
2012-03-02    1.2062455
2012-03-05    1.1957168
2012-03-06    1.1866926
2012-03-07    1.1972211
2012-03-08    1.2036129
2012-03-09    1.2028611
2012-03-12    1.2047411
2012-03-13    1.2284296
2012-03-14    1.2321901
2012-03-15    1.2351979
2012-03-16    1.2257978
2012-03-19    1.2107574
2012-03-20    1.2028611
2012-03-21    1.1998529
2012-03-22    1.2032372
2012-03-23    1.2036129
2012-03-26    1.2254220
2012-03-27    1.2227898
2012-03-28    1.2103813
2012-03-29    1.2077496
2012-03-30    1.2130135
Name: Adj Close, dtype: float64
2012-04-30 00:00:00
Date
2012-04-02    1.2141412
2012-04-03    1.2009810
2012-04-04    1.1735324
2012-04-05    1.1851887
2012-04-09    1.1693963
2012-04-10    1.1457076
2012-04-11    1.1411952
2012-04-12    1.1648842
2012-04-13    1.1584920
2012-04-16    1.1686441
2012-04-17    1.1821806
2012-04-18    1.1708999
2012-04-19    1.1660117
2012-04-20    1.2190296
2012-04-23    1.2077496
2012-04-24    1.2002291
2012-04-25    1.2107574
2012-04-26    1.2073731
2012-04-27    1.2024852
2012-04-30    1.2039893
Name: Adj Close, dtype: float64
2012-05-31 00:00:00
Date
2012-05-01    1.2036129
2012-05-02    1.1957168
2012-05-03    1.1942128
2012-05-04    1.1648842
2012-05-07    1.1524758
2012-05-08    1.1468354
2012-05-09    1.1566120
2012-05-10    1.1558598
2012-05-11    1.1716523
2012-05-14    1.1536041
2012-05-15    1.1433849
2012-05-16    1.1316521
2012-05-17    1.1248393
2012-05-18    1.1078078
2012-05-21    1.1259748
2012-05-22    1.1263531
2012-05-23    1.1017521
2012-05-24    1.1002378
2012-05-25    1.0998597
2012-05-29    1.1187835
2012-05-30    1.1104572
2012-05-31    1.1047800
Name: Adj Close, dtype: float64
2012-06-30 00:00:00
Date
2012-06-01    1.0767725
2012-06-04    1.0805570
2012-06-05    1.0790434
2012-06-06    1.1108356
2012-06-07    1.1062936
2012-06-08    1.1221901
2012-06-11    1.0938042
2012-06-12    1.1085646
2012-06-13    1.1025091
2012-06-14    1.1104572
2012-06-15    1.1361936
2012-06-18    1.1293811
2012-06-19    1.1619302
2012-06-20    1.1706354
2012-06-21    1.1407355
2012-06-22    1.1619302
2012-06-25    1.1305164
2012-06-26    1.1361936
2012-06-27    1.1418706
2012-06-28    1.1320302
2012-06-29    1.1577670
Name: Adj Close, dtype: float64
2012-07-31 00:00:00
Date
2012-07-02    1.1566314
2012-07-03    1.1642013
2012-07-05    1.1619302
2012-07-06    1.1426277
2012-07-09    1.1354367
2012-07-10    1.1255963
2012-07-11    1.1089431
2012-07-12    1.0835850
2012-07-13    1.1123494
2012-07-16    1.1142416
2012-07-17    1.1225683
2012-07-18    1.1524682
2012-07-19    1.1607948
2012-07-20    1.1399784
2012-07-23    1.1081864
2012-07-24    1.1032661
2012-07-25    1.0911551
2012-07-26    1.1036441
2012-07-27    1.1263531
2012-07-30    1.1218115
2012-07-31    1.1153774
Name: Adj Close, dtype: float64
2012-08-31 00:00:00
Date
2012-08-01    1.1131063
2012-08-02    1.1047800
2012-08-03    1.1259748
2012-08-06    1.1335444
2012-08-07    1.1452768
2012-08-08    1.1479265
2012-08-09    1.1543605
2012-08-10    1.1513331
2012-08-13    1.1501974
2012-08-14    1.1479112
2012-08-15    1.1505786
2012-08-16    1.1726759
2012-08-17    1.1772473
2012-08-20    1.1711514
2012-08-21    1.1734374
2012-08-22    1.1635321
2012-08-23    1.1528641
2012-08-24    1.1642938
2012-08-27    1.1692468
2012-08-28    1.1669609
2012-08-29    1.1677230
2012-08-30    1.1551504
2012-08-31    1.1741995
Name: Adj Close, dtype: float64
2012-09-30 00:00:00
Date
2012-09-04    1.1578171
2012-09-05    1.1578171
2012-09-06    1.1943917
2012-09-07    1.1791523
2012-09-10    1.1703896
2012-09-11    1.1730565
2012-09-12    1.1726759
2012-09-13    1.1787713
2012-09-14    1.1890579
2012-09-17    1.1890579
2012-09-18    1.1879149
2012-09-19    1.1829621
2012-09-20    1.1982017
2012-09-21    1.1882961
2012-09-24    1.1726759
2012-09-25    1.1578171
2012-09-26    1.1494354
2012-09-27    1.1490542
2012-09-28    1.1338152
Name: Adj Close, dtype: float64
2012-10-31 00:00:00
Date
2012-10-01    1.1235284
2012-10-02    1.1300050
2012-10-03    1.1376250
2012-10-04    1.1441015
2012-10-05    1.1372437
2012-10-08    1.1345767
2012-10-09    1.1155279
2012-10-10    1.1040982
2012-10-11    1.1029549
2012-10-12    1.1124799
2012-10-15    1.1242901
2012-10-16    1.1235284
2012-10-17    1.1273383
2012-10-18    1.1239092
2012-10-19    1.0911445
2012-10-22    1.0667615
2012-10-23    1.0686663
2012-10-24    1.0629514
2012-10-25    1.0621894
2012-10-26    1.0747621
2012-10-31    1.0873346
Name: Adj Close, dtype: float64
2012-11-30 00:00:00
Date
2012-11-01    1.1246715
2012-11-02    1.1239092
2012-11-05    1.1288620
2012-11-06    1.1376250
2012-11-07    1.1079080
2012-11-08    1.0976212
2012-11-09    1.0983833
2012-11-12    1.0751431
2012-11-13    1.0405726
2012-11-14    1.0309695
2012-11-15    1.0240553
2012-11-16    1.0186779
2012-11-19    1.0267444
2012-11-20    1.0259759
2012-11-21    1.0351949
2012-11-23    1.0640038
2012-11-26    1.0520960
2012-11-27    1.0401884
2012-11-28    1.0509439
2012-11-29    1.0351949
2012-11-30    1.0225192
Name: Adj Close, dtype: float64
2012-12-31 00:00:00
Date
2012-12-03    1.0152208
2012-12-04    1.0129162
2012-12-05    1.0244396
2012-12-06    1.0267444
2012-12-07    1.0163732
2012-12-10    1.0348105
2012-12-11    1.0494071
2012-12-12    1.0463345
2012-12-13    1.0413408
2012-12-14    1.0298175
2012-12-17    1.0409566
2012-12-18    1.0586259
2012-12-19    1.0490230
2012-12-20    1.0632355
2012-12-21    1.0544007
2012-12-24    1.0394201
2012-12-26    1.0317379
2012-12-27    1.0355791
2012-12-28    1.0198301
2012-12-31    1.0259759
Name: Adj Close, dtype: float64
2013-01-31 00:00:00
Date
2013-01-02    1.0609308
2013-01-03    1.0467183
2013-01-04    1.0271283
2013-01-07    1.0252080
2013-01-08    1.0198301
2013-01-09    1.0255917
2013-01-10    1.0163732
2013-01-11    1.0305857
2013-01-14    1.0328903
2013-01-15    1.0451820
2013-01-16    1.0386520
2013-01-17    1.0467183
2013-01-18    1.0467183
2013-01-22    1.0428773
2013-01-23    1.0605465
2013-01-24    1.0613150
2013-01-25    1.0709175
2013-01-28    1.0720701
2013-01-29    1.0759113
2013-01-30    1.0697655
2013-01-31    1.0544007
Name: Adj Close, dtype: float64
2013-02-28 00:00:00
Date
2013-02-01    1.0728385
2013-02-04    1.0540166
2013-02-05    1.0563211
2013-02-06    1.0501755
2013-02-07    1.0478708
2013-02-08    1.0582419
2013-02-11    1.0701495
2013-02-12    1.0709175
2013-02-13    1.0766798
2013-02-14    1.0770635
2013-02-15    1.0759113
2013-02-19    1.0863684
2013-02-20    1.0793970
2013-02-21    1.0646797
2013-02-22    1.0751367
2013-02-25    1.0600323
2013-02-26    1.0600323
2013-02-27    1.0770733
2013-02-28    1.0766856
Name: Adj Close, dtype: float64
2013-03-31 00:00:00
Date
2013-03-01    1.0824953
2013-03-04    1.0902413
2013-03-05    1.0979874
2013-03-06    1.0879176
2013-03-07    1.0898538
2013-03-08    1.0844319
2013-03-11    1.0793970
2013-03-12    1.0809460
2013-03-13    1.0813334
2013-03-14    1.0898538
2013-03-15    1.0859810
2013-03-18    1.0883047
2013-03-19    1.0914035
2013-03-20    1.0968255
2013-03-21    1.0886921
2013-03-22    1.0941143
2013-03-25    1.0906286
2013-03-26    1.0906286
2013-03-27    1.0987621
2013-03-28    1.1080570
Name: Adj Close, dtype: float64
2013-04-30 00:00:00
Date
2013-04-01    1.1080570
2013-04-02    1.1154156
2013-04-03    1.1061206
2013-04-04    1.1076696
2013-04-05    1.1115425
2013-04-08    1.1072825
2013-04-09    1.1467866
2013-04-10    1.1727359
2013-04-11    1.1208376
2013-04-12    1.1150285
2013-04-15    1.1111555
2013-04-16    1.1219996
2013-04-17    1.1165775
2013-04-18    1.1150285
2013-04-19    1.1529837
2013-04-22    1.1940370
2013-04-23    1.1851292
2013-04-24    1.2300554
2013-04-25    1.2370267
2013-04-26    1.2312175
2013-04-29    1.2629758
2013-04-30    1.2819530
Name: Adj Close, dtype: float64
2013-05-31 00:00:00
Date
2013-05-01    1.2672360
2013-05-02    1.2842772
2013-05-03    1.2970582
2013-05-06    1.3071279
2013-05-07    1.2900868
2013-05-08    1.2776934
2013-05-09    1.2649122
2013-05-10    1.2660740
2013-05-13    1.2792423
2013-05-14    1.3077131
2013-05-15    1.3201937
2013-05-16    1.3291639
2013-05-17    1.3599748
2013-05-20    1.3681650
2013-05-21    1.3591949
2013-05-22    1.3498345
2013-05-23    1.3318939
2013-05-24    1.3365744
2013-05-28    1.3658253
2013-05-29    1.3603652
2013-05-30    1.3662152
2013-05-31    1.3611449
Name: Adj Close, dtype: float64
2013-06-30 00:00:00
Date
2013-06-03    1.3880558
2013-06-04    1.3646552
2013-06-05    1.3564649
2013-06-06    1.3634850
2013-06-07    1.3911758
2013-06-10    1.3833755
2013-06-11    1.3588048
2013-06-12    1.3650454
2013-06-13    1.3541250
2013-06-14    1.3416446
2013-06-17    1.3650454
2013-06-18    1.3642651
2013-06-19    1.3490545
2013-06-20    1.3061534
2013-06-21    1.2975726
2013-06-24    1.3151235
2013-06-25    1.3131735
2013-06-26    1.3396943
2013-06-27    1.3502249
2013-06-28    1.3471045
Name: Adj Close, dtype: float64
2013-07-31 00:00:00
Date
2013-07-01    1.3400845
2013-07-02    1.3237037
2013-07-03    1.3264336
2013-07-05    1.3342342
2013-07-08    1.3389141
2013-07-09    1.3396943
2013-07-10    1.3533450
2013-07-11    1.3919558
2013-07-12    1.3911758
2013-07-15    1.4106763
2013-07-16    1.4145767
2013-07-17    1.3939066
2013-07-18    1.3822057
2013-07-19    1.2246405
2013-07-22    1.2484311
2013-07-23    1.2410210
2013-07-24    1.2464812
2013-07-25    1.2242505
2013-07-26    1.2332209
2013-07-29    1.2301006
2013-07-30    1.2421911
2013-07-31    1.2418013
Name: Adj Close, dtype: float64
2013-08-31 00:00:00
Date
2013-08-01    1.2351707
2013-08-02    1.2437513
2013-08-05    1.2363410
2013-08-06    1.2316608
2013-08-07    1.2503815
2013-08-08    1.2827522
2013-08-09    1.2753425
2013-08-12    1.2819723
2013-08-13    1.2658691
2013-08-14    1.2705823
2013-08-15    1.2485876
2013-08-16    1.2489804
2013-08-19    1.2328773
2013-08-20    1.2419109
2013-08-21    1.2415183
2013-08-22    1.2721534
2013-08-23    1.3648454
2013-08-26    1.3412791
2013-08-27    1.3063238
2013-08-28    1.2968974
2013-08-29    1.3177138
2013-08-30    1.3118222
Name: Adj Close, dtype: float64
2013-09-30 00:00:00
Date
2013-09-03    1.2521228
2013-09-04    1.2254147
2013-09-05    1.2265932
2013-09-06    1.2234511
2013-09-09    1.2434819
2013-09-10    1.2721534
2013-09-11    1.2859001
2013-09-12    1.2839359
2013-09-13    1.2972901
2013-09-16    1.2882565
2013-09-17    1.2933625
2013-09-18    1.3086801
2013-09-19    1.3212486
2013-09-20    1.2878639
2013-09-23    1.2859001
2013-09-24    1.2745100
2013-09-25    1.2768666
2013-09-26    1.2870783
2013-09-27    1.3067163
2013-09-30    1.3071089
Name: Adj Close, dtype: float64
2013-10-31 00:00:00
Date
2013-10-01    1.3188917
2013-10-02    1.3322457
2013-10-03    1.3298894
2013-10-04    1.3306748
2013-10-07    1.3078948
2013-10-08    1.2965045
2013-10-09    1.2988609
2013-10-10    1.3259618
2013-10-11    1.3404940
2013-10-14    1.3530626
2013-10-15    1.3546335
2013-10-16    1.3605247
2013-10-17    1.3715216
2013-10-18    1.3730928
2013-10-21    1.3742715
2013-10-22    1.3581682
2013-10-23    1.3259618
2013-10-24    1.3243906
2013-10-25    1.4033353
2013-10-28    1.3970513
2013-10-29    1.3950875
2013-10-30    1.3958736
2013-10-31    1.3907675
Name: Adj Close, dtype: float64
2013-11-30 00:00:00
Date
2013-11-01    1.3954806
2013-11-04    1.4115839
2013-11-05    1.4390765
2013-11-06    1.4995618
2013-11-07    1.4728540
2013-11-08    1.4838516
2013-11-11    1.4763889
2013-11-12    1.4673554
2013-11-13    1.4987763
2013-11-14    1.4932774
2013-11-15    1.4862080
2013-11-18    1.4610715
2013-11-19    1.4539485
2013-11-20    1.4674033
2013-11-21    1.4800673
2013-11-22    1.4867943
2013-11-25    1.4895648
2013-11-26    1.4780883
2013-11-27    1.4879821
2013-11-29    1.5089566
Name: Adj Close, dtype: float64
2013-12-31 00:00:00
Date
2013-12-02    1.5216199
2013-12-03    1.5160797
2013-12-04    1.5410113
2013-12-05    1.5038116
2013-12-06    1.5180580
2013-12-09    1.5319088
2013-12-10    1.5081643
2013-12-11    1.4883779
2013-12-12    1.4729441
2013-12-13    1.4519695
2013-12-16    1.4598840
2013-12-17    1.4452416
2013-12-18    1.4476163
2013-12-19    1.4345572
2013-12-20    1.4563230
2013-12-23    1.4491994
2013-12-24    1.4674033
2013-12-26    1.4816504
2013-12-27    1.4757145
2013-12-30    1.4757145
Name: Adj Close, dtype: float64

In [30]:
len(msft_monthly_cum_ret)
# 24 groups confirmed.

24

In [31]:
msft_monthly_cum_ret.size()
# size of each group.

Date
2012-01-31    20
2012-02-29    20
2012-03-31    22
2012-04-30    20
2012-05-31    22
2012-06-30    21
2012-07-31    21
2012-08-31    23
2012-09-30    19
2012-10-31    21
2012-11-30    21
2012-12-31    20
2013-01-31    21
2013-02-28    19
2013-03-31    20
2013-04-30    22
2013-05-31    22
2013-06-30    20
2013-07-31    22
2013-08-31    22
2013-09-30    20
2013-10-31    23
2013-11-30    20
2013-12-31    20
Freq: M, Name: Adj Close, dtype: int64

In [32]:
msft_monthly_cum_ret.mean()

Date
2012-01-31    1.0686745
2012-02-29    1.1556974
2012-03-31    1.2105693
2012-04-30    1.1846434
2012-05-31    1.1405158
2012-06-30    1.1233434
2012-07-31    1.1262451
2012-08-31    1.1536292
2012-09-30    1.1727558
2012-10-31    1.1073818
2012-11-30    1.0648219
2012-12-31    1.0358095
2013-01-31    1.0462062
2013-02-28    1.0678732
2013-03-31    1.0898927
2013-04-30    1.1568916
2013-05-31    1.3204530
2013-06-30    1.3507122
2013-07-31    1.3124111
2013-08-31    1.2726697
2013-09-30    1.2773968
2013-10-31    1.3503983
2013-11-30    1.4719146
2013-12-31    1.4823625
Freq: M, Name: Adj Close, dtype: float64

In [33]:
msft_cum_ret['2/2012'].mean()
# to compare and confirm the mean of feb in immediately above series. Confirmed and the same.

1.1556973503883246

In [34]:
## The above work is almost the end of page 94 in the book. After that, for about 3 pages, the discussion in the book cannot be
# implemented here since there is change in the newer version of pandas. But what we can do something extra and interesting follows
# as:

In [35]:
msft.head(5)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6678486
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1777744
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.4044075
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7524548
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4529667

In [36]:
msft_resample = msft.resample('M')
# the frequency has been changed to Monthly from Daily.

In [37]:
for i, k in msft_resample:
    print(i)
    print(k)
# the data has been grouped on monthly basis into 24 groups since we have 24 months.

2012-01-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-01-03  26.9599991  26.3899994  26.5499992  26.7700005   64731500.0
2012-01-04  27.4699993  26.7800007  26.8199997  27.3999996   80516100.0
2012-01-05  27.7299995  27.2900009  27.3799992  27.6800003   56081400.0
2012-01-06  28.1900005  27.5300007  27.5300007  28.1100006   99455500.0
2012-01-09  28.1000004  27.7199993  28.0499992  27.7399998   59706800.0
2012-01-10  28.1499996  27.7500000  27.9300003  27.8400002   60014400.0
2012-01-11  27.9799995  27.3700008  27.4300003  27.7199993   65582400.0
2012-01-12  28.0200005  27.6499996  27.8700008  28.0000000   49370800.0
2012-01-13  28.2500000  27.7900009  27.9300003  28.2500000   60196100.0
2012-01-17  28.6499996  28.1700001  28.3999996  28.2600002   72395300.0
2012-01-18  28.3999996  27.9699993  28.3099995  28.2299995   64860600.0
2012-01-19  28.4400005  28.0300007  28.1599998  28.1200008   74053500.0
2012-01-20  29.7399998  28.7500000  28.8199997  29.7099991  165902900.0
2012-01-23  29.9500008  29.3500004  29.5499992  29.7299995   76078100.0
2012-01-24  29.5699997  29.1800003  29.4699993  29.3400002   51703300.0
2012-01-25  29.6499996  29.0699997  29.0699997  29.5599995   59231700.0
2012-01-26  29.7000008  29.3999996  29.6100006  29.5000000   49102800.0
2012-01-27  29.5300007  29.1700001  29.4500008  29.2299995   44187700.0
2012-01-30  29.6200008  28.8299999  28.9699993  29.6100006   51114800.0
2012-01-31  29.7000008  29.2299995  29.6599998  29.5300007   50572400.0

             Adj Close
Date
2012-01-03  21.6678486
2012-01-04  22.1777744
2012-01-05  22.4044075
2012-01-06  22.7524548
2012-01-09  22.4529667
2012-01-10  22.5339127
2012-01-11  22.4367809
2012-01-12  22.6634140
2012-01-13  22.8657722
2012-01-17  22.8738651
2012-01-18  22.8495770
2012-01-19  22.7605495
2012-01-20  24.0474987
2012-01-23  24.0636940
2012-01-24  23.7480259
2012-01-25  23.9260921
2012-01-26  23.8775291
2012-01-27  23.6589909
2012-01-30  23.9665623
2012-01-31  23.9018116
2012-02-29 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-02-01  30.0499992  29.7600002  29.7900009  29.8899994  67409900.0
2012-02-02  30.1700001  29.7099991  29.8999996  29.9500008  52223300.0
2012-02-03  30.3999996  30.0900002  30.1399994  30.2399998  41838500.0
2012-02-06  30.2199993  29.9699993  30.0400009  30.2000008  28039700.0
2012-02-07  30.4899998  30.0499992  30.1499996  30.3500004  39242400.0
2012-02-08  30.6700001  30.2199993  30.2600002  30.6599998  49659100.0
2012-02-09  30.7999992  30.4799995  30.6800003  30.7700005  50481600.0
2012-02-10  30.7999992  30.3600006  30.6399994  30.5000000  44605300.0
2012-02-13  30.7700005  30.4300003  30.6299992  30.5799999  33319800.0
2012-02-14  30.4599991  29.8500004  30.3299999  30.2500000  59644000.0
2012-02-15  30.3899994  30.0300007  30.3299999  30.0499992  43311300.0
2012-02-16  31.5499992  30.2999992  30.3099995  31.2900009  94705100.0
2012-02-17  31.3199997  30.9500008  31.2000008  31.2500000  70036500.0
2012-02-21  31.6100006  31.1499996  31.1800003  31.4400005  50829900.0
2012-02-22  31.6800003  31.1800003  31.4500008  31.2700005  49253200.0
2012-02-23  31.5900002  31.0000000  31.2000008  31.3700008  35034700.0
2012-02-24  31.5000000  31.2399998  31.4799995  31.4799995  35575400.0
2012-02-27  31.5000000  31.1000004  31.2399998  31.3500004  34568400.0
2012-02-28  31.9300003  31.3799992  31.4099998  31.8700008  45230600.0
2012-02-29  32.0000000  31.6100006  31.8899994  31.7399998  59323600.0

             Adj Close
Date
2012-02-01  24.1932011
2012-02-02  24.2417641
2012-02-03  24.4764881
2012-02-06  24.4441128
2012-02-07  24.5655251
2012-02-08  24.8164387
2012-02-09  24.9054699
2012-02-10  24.6869335
2012-02-13  24.7516899
2012-02-14  24.6457767
2012-02-15  24.4828262
2012-02-16  25.4930992
2012-02-17  25.4605103
2012-02-21  25.6153107
2012-02-22  25.4768066
2012-02-23  25.5582809
2012-02-24  25.6478977
2012-02-27  25.5419807
2012-02-28  25.9656544
2012-02-29  25.8597374
2012-03-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-03-01  32.3899994  31.8500004  31.9300003  32.2900009  77344100.0
2012-03-02  32.4399986  32.0000000  32.3100014  32.0800018  47314200.0
2012-03-05  32.0499992  31.6200008  32.0099983  31.7999992  45240000.0
2012-03-06  31.9799995  31.4899998  31.5400009  31.5599995  51932900.0
2012-03-07  31.9200001  31.5300007  31.6700001  31.8400002  34340400.0
2012-03-08  32.2099991  31.8999996  32.0400009  32.0099983  36747400.0
2012-03-09  32.1599998  31.9200001  32.0999985  31.9899998  34628400.0
2012-03-12  32.2000008  31.8199997  31.9699993  32.0400009  34073600.0
2012-03-13  32.6899986  32.1500015  32.2400017  32.6699982  48951700.0
2012-03-14  32.8800011  32.4900017  32.5299988  32.7700005  41986900.0
2012-03-15  32.9399986  32.5800018  32.7900009  32.8499985  49068300.0
2012-03-16  32.9500008  32.5000000  32.9099998  32.5999985  65626400.0
2012-03-19  32.6100006  32.1500015  32.5400009  32.2000008  44789200.0
2012-03-20  32.1500015  31.7399998  32.0999985  31.9899998  41566800.0
2012-03-21  32.1500015  31.8199997  31.9599991  31.9099998  37928600.0
2012-03-22  32.0900002  31.7900009  31.8099995  32.0000000  31749500.0
2012-03-23  32.1100006  31.7199993  32.0999985  32.0099983  35912200.0
2012-03-26  32.6100006  32.1500015  32.1899986  32.5900002  36758300.0
2012-03-27  32.7000008  32.4000015  32.6500015  32.5200005  36274900.0
2012-03-28  32.7000008  32.0400009  32.5200005  32.1899986  41344800.0
2012-03-29  32.1899986  31.8099995  32.0600014  32.1199989  37038500.0
2012-03-30  32.4099998  32.0400009  32.4000015  32.2599983  31749400.0

             Adj Close
Date
2012-03-01  26.3078270
2012-03-02  26.1367455
2012-03-05  25.9086113
2012-03-06  25.7130756
2012-03-07  25.9412060
2012-03-08  26.0797024
2012-03-09  26.0634117
2012-03-12  26.1041470
2012-03-13  26.6174259
2012-03-14  26.6989079
2012-03-15  26.7640820
2012-03-16  26.5604019
2012-03-19  26.2345085
2012-03-20  26.0634117
2012-03-21  25.9982319
2012-03-22  26.0715618
2012-03-23  26.0797024
2012-03-26  26.5522575
2012-03-27  26.4952240
2012-03-28  26.2263584
2012-03-29  26.1693344
2012-03-30  26.2833939
2012-04-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-04-02  32.4599991  31.9500008  32.2200012  32.2900009   35853600.0
2012-04-03  32.1899986  31.6599998  32.1599998  31.9400005   42752100.0
2012-04-04  31.6900005  31.0499992  31.6599998  31.2099991   49455900.0
2012-04-05  31.6299992  31.0499992  31.1499996  31.5200005   50368600.0
2012-04-09  31.3999996  30.9699993  31.2199993  31.1000004   31056400.0
2012-04-10  31.1900005  30.2999992  31.0599995  30.4699993   54131300.0
2012-04-11  30.5300007  30.2299995  30.4300003  30.3500004   43014000.0
2012-04-12  31.0400009  30.4200001  30.4799995  30.9799995   38304000.0
2012-04-13  31.1599998  30.7199993  30.8899994  30.8099995   39749200.0
2012-04-16  31.1900005  30.7700005  30.9899998  31.0799999   38124800.0
2012-04-17  31.6100006  31.2000008  31.2700005  31.4400005   34361500.0
2012-04-18  31.3099995  31.0400009  31.2800007  31.1399994   40552900.0
2012-04-19  31.6800003  30.9400005  31.1299992  31.0100002   54781200.0
2012-04-20  32.8899994  32.0499992  32.1500015  32.4199982  106045000.0
2012-04-23  32.5000000  32.0299988  32.3100014  32.1199989   61398200.0
2012-04-24  32.5200005  31.8299999  32.2099991  31.9200001   40871100.0
2012-04-25  32.3199997  31.8700008  31.9200001  32.2000008   62495500.0
2012-04-26  32.2299995  31.9200001  32.1199989  32.1100006   40308100.0
2012-04-27  32.2200012  31.8799992  32.1199989  31.9799995   41419100.0
2012-04-30  32.1100006  31.9200001  31.9799995  32.0200005   35697200.0

             Adj Close
Date
2012-04-02  26.3078270
2012-04-03  26.0226746
2012-04-04  25.4279213
2012-04-05  25.6804886
2012-04-09  25.3383026
2012-04-10  24.8250179
2012-04-11  24.7272453
2012-04-12  25.2405338
2012-04-13  25.1020298
2012-04-16  25.3220024
2012-04-17  25.6153107
2012-04-18  25.3708820
2012-04-19  25.2649651
2012-04-20  26.4137497
2012-04-23  26.1693344
2012-04-24  26.0063820
2012-04-25  26.2345085
2012-04-26  26.1611767
2012-04-27  26.0552673
2012-04-30  26.0878582
2012-05-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-05-01  32.3400002  31.9500008  32.0499992  32.0099983  43832300.0
2012-05-02  31.9300003  31.6399994  31.8500004  31.7999992  37385300.0
2012-05-03  31.8999996  31.6100006  31.8799992  31.7600002  31501300.0
2012-05-04  31.5699997  30.9200001  31.4500008  30.9799995  57927200.0
2012-05-07  30.8600006  30.5699997  30.7000008  30.6499996  48641400.0
2012-05-08  30.7800007  30.1700001  30.4799995  30.5000000  46328300.0
2012-05-09  30.8299999  30.1000004  30.1900005  30.7600002  50309300.0
2012-05-10  31.0200005  30.4500008  30.8600006  30.7399998  43839200.0
2012-05-11  31.5400009  30.6900005  30.6900005  31.1599998  43459300.0
2012-05-14  31.0400009  30.6399994  30.8199997  30.6800003  40528900.0
2012-05-15  30.7999992  30.1499996  30.6399994  30.2099991  61822800.0
2012-05-16  30.3199997  29.7399998  30.3099995  29.8999996  60083700.0
2012-05-17  30.2099991  29.7099991  29.9899998  29.7199993  48484000.0
2012-05-18  29.8099995  29.1700001  29.7900009  29.2700005  56205300.0
2012-05-21  29.7900009  29.0599995  29.1000004  29.7500000  38787900.0
2012-05-22  29.8799992  29.5000000  29.6900005  29.7600002  39504900.0
2012-05-23  29.3999996  28.6399994  29.3500004  29.1100006  65171000.0
2012-05-24  29.2999992  28.7600002  29.1599998  29.0699997  52575000.0
2012-05-25  29.3600006  29.0100002  29.2000008  29.0599995  29507200.0
2012-05-29  29.7199993  29.2199993  29.3799992  29.5599995  37758800.0
2012-05-30  29.4799995  29.1200008  29.3500004  29.3400002  41585500.0
2012-05-31  29.4200001  28.9400005  29.2999992  29.1900005  39134000.0

             Adj Close
Date
2012-05-01  26.0797024
2012-05-02  25.9086113
2012-05-03  25.8760223
2012-05-04  25.2405338
2012-05-07  24.9716702
2012-05-08  24.8494549
2012-05-09  25.0612926
2012-05-10  25.0449944
2012-05-11  25.3871841
2012-05-14  24.9961185
2012-05-15  24.7746906
2012-05-16  24.5204659
2012-05-17  24.3728466
2012-05-18  24.0038109
2012-05-21  24.3974514
2012-05-22  24.4056492
2012-05-23  23.8725986
2012-05-24  23.8397865
2012-05-25  23.8315926
2012-05-29  24.2416306
2012-05-30  24.0612183
2012-05-31  23.9382057
2012-06-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-06-01  28.9599991  28.4400005  28.7600002  28.4500008  56634300.0
2012-06-04  28.7800007  28.3199997  28.6200008  28.5499992  47926300.0
2012-06-05  28.7500000  28.3899994  28.5100002  28.5100002  45715400.0
2012-06-06  29.3700008  28.8099995  28.8799992  29.3500004  46860500.0
2012-06-07  29.7000008  29.1700001  29.6399994  29.2299995  37792800.0
2012-06-08  29.6800003  29.0499992  29.2099991  29.6499996  42551100.0
2012-06-11  29.8099995  28.8199997  29.7299995  28.8999996  46361900.0
2012-06-12  29.2999992  28.8400002  29.1000004  29.2900009  35337900.0
2012-06-13  29.4400005  29.0499992  29.2199993  29.1299992  32984600.0
2012-06-14  29.4599991  28.8799992  29.3299999  29.3400002  39458900.0
2012-06-15  30.0799999  29.4899998  29.5900002  30.0200005  62314400.0
2012-06-18  30.0300007  29.7099991  29.9899998  29.8400002  58679900.0
2012-06-19  31.1100006  30.0499992  30.1900005  30.7000008  75725800.0
2012-06-20  31.0499992  30.6399994  30.9300003  30.9300003  36257100.0
2012-06-21  31.1399994  30.0599995  30.9599991  30.1399994  48456600.0
2012-06-22  30.7299995  30.0300007  30.2999992  30.7000008  45098100.0
2012-06-25  30.3199997  29.6200008  30.2999992  29.8700008  42217200.0
2012-06-26  30.2700005  29.9400005  30.0000000  30.0200005  38421300.0
2012-06-27  30.5000000  30.0300007  30.1900005  30.1700001  33781700.0
2012-06-28  30.0499992  29.4200001  29.9799995  29.9099998  45328400.0
2012-06-29  30.6900005  30.1399994  30.4500008  30.5900002  55227200.0

             Adj Close
Date
2012-06-01  23.3313427
2012-06-04  23.4133453
2012-06-05  23.3805485
2012-06-06  24.0694180
2012-06-07  23.9710026
2012-06-08  24.3154449
2012-06-11  23.7003841
2012-06-12  24.0202103
2012-06-13  23.8889999
2012-06-14  24.0612183
2012-06-15  24.6188717
2012-06-18  24.4712582
2012-06-19  25.1765270
2012-06-20  25.3651505
2012-06-21  24.7172832
2012-06-22  25.1765270
2012-06-25  24.4958572
2012-06-26  24.6188717
2012-06-27  24.7418785
2012-06-28  24.5286579
2012-06-29  25.0863209
2012-07-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-07-02  30.6200008  30.2099991  30.6200008  30.5599995  30589100.0
2012-07-03  30.7600002  30.1700001  30.2299995  30.7600002  20938100.0
2012-07-05  30.7800007  30.3799992  30.5900002  30.7000008  28801900.0
2012-07-06  30.7000008  29.9500008  30.6100006  30.1900005  38294800.0
2012-07-09  30.2299995  29.7800007  30.1200008  30.0000000  30680800.0
2012-07-10  30.2199993  29.5100002  30.0799999  29.7399998  37534100.0
2012-07-11  29.7399998  29.1100006  29.7099991  29.2999992  39184900.0
2012-07-12  29.1800003  28.5400009  29.1499996  28.6299992  63523600.0
2012-07-13  29.4799995  28.7199993  28.7600002  29.3899994  39085000.0
2012-07-16  29.5300007  29.0400009  29.4799995  29.4400005  27900600.0
2012-07-17  29.8600006  29.2000008  29.6399994  29.6599998  33771300.0
2012-07-18  30.4500008  29.4599991  29.6000004  30.4500008  41090400.0
2012-07-19  30.7999992  30.3799992  30.5100002  30.6700001  46663200.0
2012-07-20  31.0499992  30.0499992  31.0000000  30.1200008  64021700.0
2012-07-23  29.5799999  29.0100002  29.5699997  29.2800007  55151900.0
2012-07-24  29.3600006  28.8999996  29.2399998  29.1499996  47723300.0
2012-07-25  29.3299999  28.7800007  29.2399998  28.8299999  45579500.0
2012-07-26  29.5000000  29.0900002  29.2299995  29.1599998  45301400.0
2012-07-27  29.8500004  29.1800003  29.4799995  29.7600002  44242600.0
2012-07-30  29.8199997  29.4599991  29.7500000  29.6399994  28905000.0
2012-07-31  29.7099991  29.3299999  29.4799995  29.4699993  37620900.0

             Adj Close
Date
2012-07-02  25.0617142
2012-07-03  25.2257385
2012-07-05  25.1765270
2012-07-06  24.7582836
2012-07-09  24.6024704
2012-07-10  24.3892498
2012-07-11  24.0284119
2012-07-12  23.4789562
2012-07-13  24.1022186
2012-07-16  24.1432190
2012-07-17  24.3236408
2012-07-18  24.9715061
2012-07-19  25.1519260
2012-07-20  24.7008801
2012-07-23  24.0120144
2012-07-24  23.9054031
2012-07-25  23.6429825
2012-07-26  23.9135933
2012-07-27  24.4056492
2012-07-30  24.3072414
2012-07-31  24.1678276
2012-08-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-08-01  29.6499996  29.2099991  29.5900002  29.4099998  31721800.0
2012-08-02  29.5300007  28.9699993  29.2099991  29.1900005  39520500.0
2012-08-03  29.9400005  29.4799995  29.5300007  29.7500000  35859400.0
2012-08-06  30.1100006  29.8099995  30.0000000  29.9500008  27471800.0
2012-08-07  30.3500004  29.8700008  30.0699997  30.2600002  28002900.0
2012-08-08  30.4699993  30.1100006  30.2099991  30.3299999  26257600.0
2012-08-09  30.6499996  30.2999992  30.3899994  30.5000000  24920800.0
2012-08-10  30.6200008  30.2500000  30.5000000  30.4200001  27810300.0
2012-08-13  30.4599991  30.1599998  30.3500004  30.3899994  23049100.0
2012-08-14  30.3899994  30.0100002  30.2999992  30.1299992  34551400.0
2012-08-15  30.2800007  30.0200005  30.1100006  30.2000008  24351000.0
2012-08-16  30.9400005  30.2600002  30.3600006  30.7800007  35787200.0
2012-08-17  30.9200001  30.5900002  30.9200001  30.8999996  32589900.0
2012-08-20  30.8500004  30.5799999  30.8199997  30.7399998  23737700.0
2012-08-21  30.9599991  30.6100006  30.7600002  30.7999992  28822700.0
2012-08-22  30.7600002  30.4699993  30.5900002  30.5400009  33437400.0
2012-08-23  30.3999996  30.0799999  30.3899994  30.2600002  28355600.0
2012-08-24  30.6299992  30.1800003  30.2500000  30.5599995  22943300.0
2012-08-27  30.9599991  30.5900002  30.9300003  30.6900005  34691100.0
2012-08-28  30.7999992  30.5200005  30.7000008  30.6299992  23947900.0
2012-08-29  30.7500000  30.4400005  30.6499996  30.6499996  23346800.0
2012-08-30  30.6100006  30.2199993  30.5300007  30.3199997  23982100.0
2012-08-31  30.9599991  30.3799992  30.6000004  30.8199997  36590100.0

             Adj Close
Date
2012-08-01  24.1186180
2012-08-02  23.9382057
2012-08-03  24.3974514
2012-08-06  24.5614681
2012-08-07  24.8156853
2012-08-08  24.8730984
2012-08-09  25.0125084
2012-08-10  24.9469109
2012-08-13  24.9223022
2012-08-14  24.8727665
2012-08-15  24.9305630
2012-08-16  25.4093628
2012-08-17  25.5084171
2012-08-20  25.3763313
2012-08-21  25.4258633
2012-08-22  25.2112370
2012-08-23  24.9800854
2012-08-24  25.2277412
2012-08-27  25.3350620
2012-08-28  25.2855320
2012-08-29  25.3020458
2012-08-30  25.0296249
2012-08-31  25.4423771
2012-09-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-09-04  30.6599998  30.1499996  30.4500008  30.3899994   48556700.0
2012-09-05  30.5300007  30.2099991  30.2199993  30.3899994   33650000.0
2012-09-06  31.3600006  30.4599991  30.5000000  31.3500004   48371700.0
2012-09-07  31.0699997  30.7299995  31.0400009  30.9500008   42649100.0
2012-09-10  30.8999996  30.5100002  30.8299999  30.7199993   40524000.0
2012-09-11  30.9099998  30.6100006  30.6900005  30.7900009   25191800.0
2012-09-12  31.1800003  30.7299995  30.9400005  30.7800007   32775800.0
2012-09-13  31.1800003  30.3999996  30.8899994  30.9400005   45047300.0
2012-09-14  31.2500000  30.8099995  31.0100002  31.2099991   51422800.0
2012-09-17  31.2600002  31.0400009  31.1900005  31.2099991   36488500.0
2012-09-18  31.2099991  31.0300007  31.1000004  31.1800003   34542700.0
2012-09-19  31.1900005  31.0400009  31.0900002  31.0499992   48871900.0
2012-09-20  31.4799995  30.9099998  30.9500008  31.4500008   45543000.0
2012-09-21  31.6100006  31.0900002  31.4300003  31.1900005  102348900.0
2012-09-24  31.0699997  30.6399994  31.0000000  30.7800007   46825900.0
2012-09-25  31.0000000  30.3600006  30.9500008  30.3899994   54266400.0
2012-09-26  30.6000004  30.0400009  30.2800007  30.1700001   54672000.0
2012-09-27  30.3999996  29.8899994  30.1700001  30.1599998   47129900.0
2012-09-28  30.2600002  29.7399998  30.1800003  29.7600002   54229300.0

             Adj Close
Date
2012-09-04  25.0874062
2012-09-05  25.0874062
2012-09-06  25.8798981
2012-09-07  25.5496941
2012-09-10  25.3598251
2012-09-11  25.4176102
2012-09-12  25.4093628
2012-09-13  25.5414371
2012-09-14  25.7643261
2012-09-17  25.7643261
2012-09-18  25.7395611
2012-09-19  25.6322441
2012-09-20  25.9624519
2012-09-21  25.7478199
2012-09-24  25.4093628
2012-09-25  25.0874062
2012-09-26  24.9057922
2012-09-27  24.8975315
2012-09-28  24.5673370
2012-10-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-10-01  29.9799995  29.4200001  29.8099995  29.4899998  54042700.0
2012-10-02  29.8899994  29.5000000  29.6800003  29.6599998  43338900.0
2012-10-03  29.9899998  29.6700001  29.7500000  29.8600006  46655900.0
2012-10-04  30.0300007  29.5699997  29.9699993  30.0300007  43634900.0
2012-10-05  30.2500000  29.7399998  30.2299995  29.8500004  41133900.0
2012-10-08  29.9200001  29.5499992  29.6399994  29.7800007  29752000.0
2012-10-09  29.7399998  29.1800003  29.6800003  29.2800007  45121100.0
2012-10-10  29.3099995  28.9500008  29.1499996  28.9799995  47227100.0
2012-10-11  29.2500000  28.8700008  29.2199993  28.9500008  41488500.0
2012-10-12  29.3199997  28.7999992  28.9699993  29.2000008  46464700.0
2012-10-15  29.7199993  29.2500000  29.3700008  29.5100002  42440200.0
2012-10-16  29.7399998  29.3199997  29.4500008  29.4899998  47739400.0
2012-10-17  29.6399994  29.0900002  29.2999992  29.5900002  44206100.0
2012-10-18  29.7299995  29.2600002  29.6499996  29.5000000  59238500.0

In [38]:
msft_resample.mean().head(3)
# mean of high, low, open, close, volume and adj close for each month.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-31,28.6900001,28.1710001,28.3479999,28.5165000,6.7742905e+07,23.0814764
2012-02-29,30.9949998,30.5429999,30.7125000,30.8250002,4.9216615e+07,25.0414752
2012-03-31,32.3877273,31.9777278,32.1986364,32.1949996,4.2834841e+07,26.2304331

In [39]:
msft.loc['1/2012', 'Adj Close'].mean()
# confirmed that 'msft_resample.mean()' has produced mean of high, low, open, close, volume and adj close for each month.

23.081476402282714